apiVersion: v1
kind: Namespace
metadata:
  name: devops-tools
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: devops-tools  
  labels:
    app: nexus
    tier: devops
    version: v1
spec:
  type: NodePort  
  ports:
    - port: 8081
  selector: 
    app: nexus
    tier: devops
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-dep
  namespace: devops-tools  
  labels:
    app: nexus
    tier: devops
    version: v1
spec:
  selector:
    matchLabels:
      app: nexus
      tier: devops
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus
        tier: devops
        version: v1
    spec:
      terminationGracePeriodSeconds: 20    
      restartPolicy: Always   
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-blobs
              mountPath: /nexus-data
          imagePullPolicy: IfNotPresent
      volumes:
      - name: nexus-blobs
        hostPath:
          path: /host_mnt/d/nexus-data
          type: DirectoryOrCreate      
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%              
